log4r_config:
  loggers:
    - name: development
      level: DEBUG
      outputters:
      - rotatefile
      - console
  outputters:
  - type: StdoutOutputter
    name: console
    formatter:
      type: CustomFileFormatter
  - type: DateFileOutputter
    name: rotatefile
    filename: "patients_development.log"
    date_pattern: "%Y%m%d"
    dirname: "log/"
    formatter:
      type: CustomFileFormatter
