log4r_config:
  loggers:
    - name: production
      level: WARN
      outputters:
      - rotatefile
  outputters:
  - type: DateFileOutputter
    name: rotatefile
    filename: "patients_production.log"
    date_pattern: "%Y%m%d"
    dirname: "log/"
    formatter:
      type: CustomFileFormatter
